Repository dan297/project-2, pull requests merged in 2021-09, with the labels that each got.

#27 image array seeding
  seeds/carData.js
Labels: bug

#30 bug: fixed issue with seeding database
  models/carModel.js
  models/reviewModel.js
  models/userModel.js
  seeds/index.js
Labels: bug

#32 added structure to controllers
  controllers/api/carRoutes.js
  controllers/api/reviewRoutes.js
  controllers/api/userRoutes.js
  controllers/homeRoutes.js
  controllers/index.js
Labels: enhancement

#62 Update readme
  README.md
  assets/login.png
Labels: documentation
